name: ente_events
description: A Flutter package for event management using event_bus, extracted from the surprise app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  event_bus: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
