# https://grafana.com/docs/loki/latest/clients/promtail/configuration/

# We don't want Promtail's HTTP / GRPC server.
server:
    disable: true

# Loki URL
# For Grafana Cloud, it can be found in the integrations section.
clients:
    - url: http://loki:3100/loki/api/v1/push

# Manually add entries for all our services. This is a bit cumbersome, but
# - Retains flexibility in file names.
# - Makes adding job labels easy.
# - Does not get in the way of logrotation.
#
# In addition, also scrape logs from all docker containers.
scrape_configs:
    - job_name: museum
      static_configs:
          - labels:
                job: museum
                host: ${HOSTNAME}
                __path__: /var/logs/museum.log

    - job_name: copycat-db
      static_configs:
          - labels:
                job: copycat-db
                host: ${HOSTNAME}
                __path__: /var/logs/copycat-db.log

    - job_name: phoenix
      static_configs:
          - labels:
                job: phoenix
                host: ${HOSTNAME}
                __path__: /var/logs/phoenix.log

    - job_name: docker
      static_configs:
          - labels:
                job: docker
                host: ${HOSTNAME}
                __path__: /var/lib/docker/containers/*/*-json.log
