// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: require_trailing_commas

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:photos/src/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_image_ml`

Future<
    (
      Uint8List,
      BigInt,
      BigInt,
      Uint8List,
      BigInt,
      BigInt,
      Uint8List,
      BigInt,
      BigInt
    )> processImageMlFromPath(
        {required String imagePath}) =>
    RustLib.instance.api
        .crateApiImageProcessingProcessImageMlFromPath(imagePath: imagePath);

Future<
    (
      Uint8List,
      BigInt,
      BigInt,
      Uint8List,
      BigInt,
      BigInt,
      Uint8List,
      BigInt,
      BigInt
    )> processImageMlFromData(
        {required List<int> rgbaData,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiImageProcessingProcessImageMlFromData(
        rgbaData: rgbaData, width: width, height: height);
