const sceneMap = new Map([
    [0, 'waterfall'],
    [1, 'snow'],
    [2, 'landscape'],
    [3, 'underwater'],
    [4, 'architecture'],
    [5, 'sunset / sunrise'],
    [6, 'blue sky'],
    [7, 'cloudy sky'],
    [8, 'greenery'],
    [9, 'autumn leaves'],
    [10, 'potrait'],
    [11, 'flower'],
    [12, 'night shot'],
    [13, 'stage concert'],
    [14, 'fireworks'],
    [15, 'candle light'],
    [16, 'neon lights'],
    [17, 'indoor'],
    [18, 'backlight'],
    [19, 'text documents'],
    [20, 'qr images'],
    [21, 'group potrait'],
    [22, 'computer screens'],
    [23, 'kids'],
    [24, 'dog'],
    [25, 'cat'],
    [26, 'macro'],
    [27, 'food'],
    [28, 'beach'],
    [29, 'mountain'],
]);

export default sceneMap;
