const sceneMap = new Map([
    [0, 'Waterfall'],
    [1, 'Snow'],
    [2, 'Landscape'],
    [3, 'Underwater'],
    [4, 'Architecture'],
    [5, 'Sunset Sunrise'],
    [6, 'Blue Sky'],
    [7, 'Cloudy Sky'],
    [8, 'Greenery'],
    [9, 'Autumn Leaves'],
    [10, 'Potrait'],
    [11, 'Flower'],
    [12, 'Night Shot'],
    [13, 'Stage Concert'],
    [14, 'Fireworks'],
    [15, 'Candle Light'],
    [16, 'Neon Lights'],
    [17, 'Indoor'],
    [18, 'Backlight'],
    [19, 'Text Documents'],
    [20, 'QR Images'],
    [21, 'Group Potrait'],
    [22, 'Computer Screens'],
    [23, 'Kids'],
    [24, 'Dog'],
    [25, 'Cat'],
    [26, 'Macro'],
    [27, 'Food'],
    [28, 'Beach'],
    [29, 'Mountain'],
]);

export default sceneMap;
