name = "files"
main = "src/index.ts"
compatibility_date = "2026-04-23"

routes = [
    { pattern = "files.ente.com", custom_domain = true },
    { pattern = "files.ente.io", custom_domain = true }
]

tail_consumers = [
    { service = "tail" }
]
