name: ente_ui
description: A Flutter package containing shared UI components, themes, and utilities for Ente apps
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  ente_base:
    path: ../../packages/base
  ente_configuration:
    path: ../../packages/configuration
  ente_logging:
    path: ../../packages/logging
  ente_strings:
    path: ../../packages/strings
  ente_utils:
    path: ../../packages/utils
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.4
  fluttertoast: ^8.1.1
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.5.3
  window_manager: ^0.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
