#!/usr/bin/env bash

# Build Ensu's UniFFI Rust static libs for the current Xcode build.
# Invoked from an Xcode "Run Script" build phase.
#
# Inputs  (from Xcode):  SRCROOT, TARGET_TEMP_DIR, PLATFORM_NAME, ARCHS,
#                        CONFIGURATION, IPHONEOS_DEPLOYMENT_TARGET,
#                        ENTE_API_ENDPOINT.
# Outputs (to $TARGET_TEMP_DIR/ensu_rust):
#           libcore.a  libdb.a  libsync.a  libinference.a
#
# UniFFI Swift bindings under $SRCROOT/Ensu/Generated/ are generated
# out-of-band by `cargo codegen ensu-ios`; this script only checks that
# they exist.

set -euo pipefail

: "${SRCROOT:?}" "${TARGET_TEMP_DIR:?}" "${PLATFORM_NAME:?}" "${ARCHS:?}"

REPO_ROOT=$(cd "$SRCROOT/../../../../.." && pwd)
GENERATED_DIR="$SRCROOT/Ensu/Generated"
OUT_DIR="$TARGET_TEMP_DIR/ensu_rust"
mkdir -p "$GENERATED_DIR" "$OUT_DIR"

# Xcode's build-phase PATH omits Homebrew and rustup's install dir.
export PATH="${CARGO_HOME:-$HOME/.cargo}/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

for tool in cargo rustup cmake; do
    command -v "$tool" >/dev/null || { echo "error: $tool not on PATH" >&2; exit 1; }
done

for name in core db sync inference; do
    for ext in .swift FFI.h FFI.modulemap; do
        [[ -f "$GENERATED_DIR/$name$ext" ]] || {
            echo "error: missing $GENERATED_DIR/$name$ext" >&2
            echo "  run: (cd $REPO_ROOT/rust && cargo codegen ensu-ios)" >&2
            exit 1
        }
    done
done

# Bake ENTE_API_ENDPOINT into a generated Swift file.
endpoint=$(printf '%s' "${ENTE_API_ENDPOINT:-}" | tr -d '\n\r' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
if [[ -n "$endpoint" ]]; then
    escaped=${endpoint//\\/\\\\}; escaped=${escaped//\"/\\\"}
    literal="\"$escaped\""
else
    literal="nil"
fi
cat >"$GENERATED_DIR/EndpointConfig.swift" <<EOF
// Generated by scripts/build-rust.sh. Do not edit manually.
enum BuildEndpointConfig {
    static let endpoint: String? = $literal
}
EOF

# Host build scripts compile against macOS; each target uses its own SDK below.
SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
TARGET_SDKROOT=$(xcrun --sdk "$PLATFORM_NAME" --show-sdk-path)
TARGET_CLANG=$(xcrun --sdk "$PLATFORM_NAME" --find clang)
export SDKROOT
[[ -n "${IPHONEOS_DEPLOYMENT_TARGET:-}" ]] && \
    export CMAKE_OSX_DEPLOYMENT_TARGET="$IPHONEOS_DEPLOYMENT_TARGET"

case "${CONFIGURATION:-Debug}" in
    Release) profile=release; cargo_flags=(--locked --release) ;;
    *)       profile=debug;   cargo_flags=(--locked) ;;
esac

rust_target_for() {
    case "$1:$2" in
        iphoneos:arm64)         echo aarch64-apple-ios ;;
        iphonesimulator:arm64)  echo aarch64-apple-ios-sim ;;
        iphonesimulator:x86_64) echo x86_64-apple-ios ;;
        *) return 1 ;;
    esac
}

build_crate() {
    local name=$1 crate_dir=$2 lib=$3
    local arch_libs=()

    echo "==> $name ($profile, $PLATFORM_NAME: $ARCHS)"

    for arch in $ARCHS; do
        local target
        target=$(rust_target_for "$PLATFORM_NAME" "$arch") || {
            echo "    skip: unsupported $PLATFORM_NAME/$arch" >&2
            continue
        }

        rustup target list --installed | grep -qx "$target" \
            || rustup target add "$target"

        local suffix
        suffix=$(echo "$target" | tr '[:lower:]-' '[:upper:]_')
        export "CARGO_TARGET_${suffix}_LINKER=$TARGET_CLANG"
        export "CFLAGS_${suffix}=-isysroot $TARGET_SDKROOT"
        export "CXXFLAGS_${suffix}=-isysroot $TARGET_SDKROOT"

        local rustflags="${RUSTFLAGS:-} -C link-arg=-isysroot -C link-arg=$TARGET_SDKROOT"
        if [[ -n "${IPHONEOS_DEPLOYMENT_TARGET:-}" ]]; then
            local min_flag
            case $PLATFORM_NAME in
                iphoneos)        min_flag=-miphoneos-version-min ;;
                iphonesimulator) min_flag=-mios-simulator-version-min ;;
            esac
            rustflags+=" -C link-arg=$min_flag=$IPHONEOS_DEPLOYMENT_TARGET"
        fi

        (cd "$crate_dir" && RUSTFLAGS="$rustflags" cargo build "${cargo_flags[@]}" --target "$target")

        local built="$crate_dir/target/$target/$profile/$lib"
        [[ -f "$built" ]] || { echo "error: expected $built" >&2; exit 1; }

        local arch_lib="$OUT_DIR/${lib%.a}_${arch}.a"
        cp "$built" "$arch_lib"
        arch_libs+=("$arch_lib")
    done

    local out="$OUT_DIR/$lib"
    rm -f "$out"
    case ${#arch_libs[@]} in
        0) echo "error: no supported archs for $name" >&2; exit 1 ;;
        1) cp "${arch_libs[0]}" "$out" ;;
        *) lipo -create "${arch_libs[@]}" -output "$out" ;;
    esac
    echo "    -> $out"
}

build_crate core      "$REPO_ROOT/rust/uniffi/core"           libcore.a
build_crate db        "$REPO_ROOT/rust/uniffi/ensu/db"        libdb.a
build_crate sync      "$REPO_ROOT/rust/uniffi/ensu/sync"      libsync.a
build_crate inference "$REPO_ROOT/rust/uniffi/ensu/inference" libinference.a
