#!/bin/sh
set -euo pipefail

# Build the UniFFI Rust static libraries for the current Xcode build platform.
#
# Outputs universal static libraries at:
#   $TARGET_TEMP_DIR/ensu_rust/libcore.a
#   $TARGET_TEMP_DIR/ensu_rust/libdb.a
#   $TARGET_TEMP_DIR/ensu_rust/libsync.a

if [ -z "${SRCROOT:-}" ] || [ -z "${TARGET_TEMP_DIR:-}" ] || [ -z "${PLATFORM_NAME:-}" ] || [ -z "${ARCHS:-}" ]; then
  echo "Missing required Xcode environment variables (SRCROOT/TARGET_TEMP_DIR/PLATFORM_NAME/ARCHS)" >&2
  exit 1
fi

REPO_ROOT="$(cd "${SRCROOT}/../../../../.." && pwd)"
OUT_DIR="${TARGET_TEMP_DIR}/ensu_rust"
GENERATED_DIR="${SRCROOT}/ensu/Generated"

mkdir -p "${OUT_DIR}"
mkdir -p "${GENERATED_DIR}"

# Use debug profile for Debug builds to speed iteration.
CARGO_FLAGS="--locked"
PROFILE="debug"
if [ "${CONFIGURATION:-Debug}" = "Release" ]; then
  CARGO_FLAGS="${CARGO_FLAGS} --release"
  PROFILE="release"
fi

write_endpoint_config() {
  endpoint_value="${ENTE_API_ENDPOINT:-}"

  endpoint_value="$(printf "%s" "${endpoint_value}")"
  endpoint_value="${endpoint_value%%$'\n'*}"
  endpoint_value="$(echo "${endpoint_value}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

  generated_file="${GENERATED_DIR}/EndpointConfig.swift"
  mkdir -p "$(dirname "${generated_file}")"

  if [ -n "${endpoint_value}" ]; then
    escaped_value="${endpoint_value//\\/\\\\}"
    escaped_value="${escaped_value//\"/\\\"}"
    endpoint_literal="\"${escaped_value}\""
  else
    endpoint_literal="nil"
  fi

  cat > "${generated_file}" <<EOF
// This file is generated by scripts/build-rust.sh. Do not edit manually.
import Foundation

enum BuildEndpointConfig {
    static let endpoint: String? = ${endpoint_literal}
}
EOF
}

bindings_missing() {
  for binding in \
    "${GENERATED_DIR}/core.swift" \
    "${GENERATED_DIR}/coreFFI.h" \
    "${GENERATED_DIR}/coreFFI.modulemap" \
    "${GENERATED_DIR}/db.swift" \
    "${GENERATED_DIR}/dbFFI.h" \
    "${GENERATED_DIR}/dbFFI.modulemap" \
    "${GENERATED_DIR}/sync.swift" \
    "${GENERATED_DIR}/syncFFI.h" \
    "${GENERATED_DIR}/syncFFI.modulemap"; do
    if [ ! -f "${binding}" ]; then
      return 0
    fi
  done

  return 1
}

generate_swift_binding() {
  crate_dir="$1"
  dylib_name="$2"

  (
    cd "${crate_dir}"
    cargo build --locked --release
    uniffi-bindgen generate "target/release/${dylib_name}" --language swift --out-dir "${GENERATED_DIR}"
  )
}

sanitize_generated_swift_bindings() {
  swift_file="$1"

  if [ ! -f "${swift_file}" ]; then
    return
  fi

  perl -0pi -e 's@try! rustCall \{ (uniffi_(?:db|sync)_fn_free_[^(]+\([^)]*\), \$0) \}@// Avoid aborting the host app if Rust-side teardown fails during process shutdown.\n        try? rustCall { $1 }@g' "${swift_file}"
}

ensure_generated_bindings() {
  if ! bindings_missing; then
    return
  fi

  if ! command -v uniffi-bindgen >/dev/null 2>&1; then
    echo "Missing generated UniFFI Swift bindings in ${GENERATED_DIR}." >&2
    echo "Install uniffi-bindgen and retry the build." >&2
    exit 1
  fi

  echo "Generating missing UniFFI Swift bindings..."
  mkdir -p "${GENERATED_DIR}"
  generate_swift_binding "${REPO_ROOT}/rust/uniffi/core" "libcore.dylib"
  generate_swift_binding "${REPO_ROOT}/rust/uniffi/ensu/db" "libdb.dylib"
  generate_swift_binding "${REPO_ROOT}/rust/uniffi/ensu/sync" "libsync.dylib"
  sanitize_generated_swift_bindings "${GENERATED_DIR}/db.swift"
  sanitize_generated_swift_bindings "${GENERATED_DIR}/sync.swift"
}

if [ "$(uname -s)" = "Darwin" ]; then
  HOST_LIB_EXT="dylib"
elif [ "$(uname -s)" = "Linux" ]; then
  HOST_LIB_EXT="so"
else
  HOST_LIB_EXT="dll"
fi

ensure_uniffi_bindgen() {
  if command -v uniffi-bindgen >/dev/null 2>&1; then
    version="$(uniffi-bindgen --version 2>/dev/null || true)"
    if printf "%s" "${version}" | grep -q "0.31."; then
      return
    fi
    echo "Found incompatible ${version}, installing uniffi-bindgen 0.31.x"
  fi

  cargo install --locked --version 0.31.0 uniffi --features cli --bin uniffi-bindgen
}

generate_swift_bindings() {
  crate_name="$1"      # e.g. core
  crate_dir="$2"       # absolute path
  lib_stem="$3"        # e.g. core

  echo "🧩 Generating Swift bindings for ${crate_name}"
  rm -f "${GENERATED_DIR}/${crate_name}.swift" \
        "${GENERATED_DIR}/${crate_name}FFI.h" \
        "${GENERATED_DIR}/${crate_name}FFI.modulemap"

  (cd "${crate_dir}" && cargo build ${CARGO_FLAGS})

  host_lib_path="${crate_dir}/target/${PROFILE}/lib${lib_stem}.${HOST_LIB_EXT}"
  if [ ! -f "${host_lib_path}" ]; then
    echo "Expected host library not found: ${host_lib_path}" >&2
    exit 1
  fi

  (cd "${crate_dir}" && uniffi-bindgen generate "${host_lib_path}" --language swift --out-dir "${GENERATED_DIR}" --crate "${crate_name}")
  sanitize_generated_swift_bindings "${GENERATED_DIR}/${crate_name}.swift"
}

# Map Xcode platform+arch to Rust target triple.
# Note: For iOS simulator on arm64, Rust uses aarch64-apple-ios-sim.
rust_target_for() {
  platform="$1"
  arch="$2"

  case "$platform" in
    iphoneos)
      if [ "$arch" = "arm64" ]; then
        echo "aarch64-apple-ios"
      else
        echo "" # unsupported
      fi
      ;;
    iphonesimulator)
      if [ "$arch" = "arm64" ]; then
        echo "aarch64-apple-ios-sim"
      elif [ "$arch" = "x86_64" ]; then
        echo "x86_64-apple-ios"
      else
        echo "" # unsupported
      fi
      ;;
    macosx)
      if [ "$arch" = "arm64" ]; then
        echo "aarch64-apple-darwin"
      elif [ "$arch" = "x86_64" ]; then
        echo "x86_64-apple-darwin"
      else
        echo "" # unsupported
      fi
      ;;
    *)
      echo "" # unsupported
      ;;
  esac
}

sdk_for_platform() {
  platform="$1"
  case "$platform" in
    iphoneos)
      echo "iphoneos";
      ;;
    iphonesimulator)
      echo "iphonesimulator";
      ;;
    macosx)
      echo "macosx";
      ;;
    *)
      echo "";
      ;;
  esac
}

TARGET_SDK_NAME="$(sdk_for_platform "${PLATFORM_NAME}")"
if [ -z "${TARGET_SDK_NAME}" ]; then
  echo "Unsupported platform: ${PLATFORM_NAME}" >&2
  exit 1
fi

TARGET_SDKROOT="$(xcrun --sdk "${TARGET_SDK_NAME}" --show-sdk-path)"
TARGET_CLANG="$(xcrun --sdk "${TARGET_SDK_NAME}" --find clang)"
HOST_SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"

# Ensure host builds (build scripts) use the macOS SDK.
export SDKROOT="${HOST_SDKROOT}"

ensure_uniffi_bindgen
ensure_generated_bindings
write_endpoint_config
generate_swift_bindings "core" "${REPO_ROOT}/rust/uniffi/core" "core"
generate_swift_bindings "db" "${REPO_ROOT}/rust/uniffi/ensu/db" "db"
generate_swift_bindings "sync" "${REPO_ROOT}/rust/uniffi/ensu/sync" "sync"

build_crate_universal() {
  crate_name="$1"           # e.g. core
  crate_dir="$2"            # absolute path
  lib_name="$3"             # e.g. libcore.a

  echo "🔧 Building ${crate_name} → ${lib_name}"

  INPUT_LIBS=""

  for arch in ${ARCHS}; do
    target="$(rust_target_for "${PLATFORM_NAME}" "$arch")"
    if [ -z "$target" ]; then
      echo "Skipping unsupported arch/platform: ${PLATFORM_NAME} ${arch}" >&2
      continue
    fi

    if ! rustup target list --installed | grep -q "^${target}$"; then
      echo "Installing Rust target ${target}..."
      rustup target add "${target}"
    fi

    target_env="$(echo "${target}" | tr '[:lower:]-' '[:upper:]_')"

    eval "export CARGO_TARGET_${target_env}_LINKER=\"${TARGET_CLANG}\""
    eval "export CFLAGS_${target_env}=\"-isysroot ${TARGET_SDKROOT}\""
    eval "export CXXFLAGS_${target_env}=\"-isysroot ${TARGET_SDKROOT}\""

    RUSTFLAGS_TARGET="${RUSTFLAGS:-} -C link-arg=-isysroot -C link-arg=${TARGET_SDKROOT}"
    if [ "${PLATFORM_NAME}" = "iphonesimulator" ] && [ -n "${IPHONEOS_DEPLOYMENT_TARGET:-}" ]; then
      RUSTFLAGS_TARGET="${RUSTFLAGS_TARGET} -C link-arg=-mios-simulator-version-min=${IPHONEOS_DEPLOYMENT_TARGET}"
    elif [ "${PLATFORM_NAME}" = "iphoneos" ] && [ -n "${IPHONEOS_DEPLOYMENT_TARGET:-}" ]; then
      RUSTFLAGS_TARGET="${RUSTFLAGS_TARGET} -C link-arg=-miphoneos-version-min=${IPHONEOS_DEPLOYMENT_TARGET}"
    fi

    echo "Building ${crate_name} for ${PLATFORM_NAME} ${arch} (${target}) [${PROFILE}]"
    (cd "${crate_dir}" && RUSTFLAGS="${RUSTFLAGS_TARGET}" cargo build ${CARGO_FLAGS} --target "${target}")

    lib_path="${crate_dir}/target/${target}/${PROFILE}/${lib_name}"
    if [ ! -f "${lib_path}" ]; then
      echo "Expected library not found: ${lib_path}" >&2
      exit 1
    fi

    arch_lib="${OUT_DIR}/${lib_name%.a}_${arch}.a"
    cp "${lib_path}" "${arch_lib}"
    INPUT_LIBS="${INPUT_LIBS} ${arch_lib}"
  done

  universal_lib="${OUT_DIR}/${lib_name}"
  rm -f "${universal_lib}"

  set -- ${INPUT_LIBS}
  if [ "$#" -eq 0 ]; then
    echo "No supported architectures found for ${crate_name} (${PLATFORM_NAME} ${ARCHS})" >&2
    exit 1
  elif [ "$#" -eq 1 ]; then
    cp "$1" "${universal_lib}"
  else
    lipo -create ${INPUT_LIBS} -output "${universal_lib}"
  fi

  echo "✅ Built ${universal_lib}"
}

build_crate_universal "core" "${REPO_ROOT}/rust/uniffi/core" "libcore.a"
build_crate_universal "db" "${REPO_ROOT}/rust/uniffi/ensu/db" "libdb.a"
build_crate_universal "sync" "${REPO_ROOT}/rust/uniffi/ensu/sync" "libsync.a"
