// Adapted from: https://github.com/deckerst/aves/blob/4a0009f4f0b63f2c4478e2531be8046c3b2e3320/lib/ref/mp4.dart

class Mp4 {
  // adapted from `metadata-extractor`
  static final brands = <String, String>{
    '3g2a': '3GPP2 Media compliant with 3GPP2 C.S0050-0 V1.0',
    '3g2b': '3GPP2 Media compliant with 3GPP2 C.S0050-A V1.0.0',
    '3g2c': '3GPP2 Media compliant with 3GPP2 C.S0050-B v1.0',
    '3ge6': '3GPP Release 6 MBMS Extended Presentations',
    '3ge7': '3GPP Release 7 MBMS Extended Presentations',
    '3gg6': '3GPP Release 6 General Profile',
    '3gp1': '3GPP Media Release 1',
    '3gp2': '3GPP Media Release 2',
    '3gp3': '3GPP Media Release 3',
    '3gp4': '3GPP Media Release 4',
    '3gp5': '3GPP Media Release 5',
    '3gp6': '3GPP Media Release 6',
    '3gs7': '3GPP Media Release 7',
    'avc1': 'MP4 Base w/ AVC ext',
    'CAEP': 'Canon Digital Camera',
    'caqv': 'Casio Digital Camera',
    'CDes': 'Convergent Design',
    'da0a': 'DMB MAF w/ MPEG Layer II aud, MOT slides, DLS, JPG/PNG/MNG images',
    'da0b':
        'DMB MAF, extending DA0A, with 3GPP timed text, DID, TVA, REL, IPMP',
    'da1a': 'DMB MAF audio with ER-BSAC audio, JPG/PNG/MNG images',
    'da1b':
        'DMB MAF, extending da1a, with 3GPP timed text, DID, TVA, REL, IPMP',
    'da2a': 'DMB MAF aud w/ HE-AAC v2 aud, MOT slides, DLS, JPG/PNG/MNG images',
    'da2b':
        'DMB MAF, extending da2a, with 3GPP timed text, DID, TVA, REL, IPMP',
    'da3a': 'DMB MAF aud with HE-AAC aud, JPG/PNG/MNG images',
    'da3b':
        'DMB MAF, extending da3a w/ BIFS, 3GPP timed text, DID, TVA, REL, IPMP',
    'dmb1':
        'DMB MAF supporting all the components defined in the specification',
    'dmpf': 'Digital Media Project',
    'drc1': 'Dirac (wavelet compression), encapsulated in ISO base media (MP4)',
    'dv1a': 'DMB MAF vid w/ AVC vid, ER-BSAC aud, BIFS, JPG/PNG/MNG images, TS',
    'dv1b':
        'DMB MAF, extending dv1a, with 3GPP timed text, DID, TVA, REL, IPMP',
    'dv2a':
        'DMB MAF vid w/ AVC vid, HE-AAC v2 aud, BIFS, JPG/PNG/MNG images, TS',
    'dv2b':
        'DMB MAF, extending dv2a, with 3GPP timed text, DID, TVA, REL, IPMP',
    'dv3a': 'DMB MAF vid w/ AVC vid, HE-AAC aud, BIFS, JPG/PNG/MNG images, TS',
    'dv3b':
        'DMB MAF, extending dv3a, with 3GPP timed text, DID, TVA, REL, IPMP',
    'dvr1': 'DVB over RTP',
    'dvt1': 'DVB over MPEG-2 Transport Stream',
    'F4V ': 'Video for Adobe Flash Player 9+',
    'F4P ': 'Protected Video for Adobe Flash Player 9+',
    'F4A ': 'Audio for Adobe Flash Player 9+',
    'F4B ': 'Audio Book for Adobe Flash Player 9+',
    'isc2': 'ISMACryp 2.0 Encrypted File',
    'iso2': 'MP4 Base Media v2',
    'isom': 'MP4 Base Media v1',
    'JP2 ': 'JPEG 2000 Image',
    'jpm ': 'JPEG 2000 Compound Image',
    'jpx ': 'JPEG 2000 w/ extensions',
    'KDDI': '3GPP2 EZmovie for KDDI 3G cellphones',
    'M4A ': 'Apple iTunes AAC-LC Audio',
    'M4B ': 'Apple iTunes AAC-LC Audio Book',
    'M4P ': 'Apple iTunes AAC-LC AES Protected Audio',
    'M4V ': 'Apple iTunes Video',
    'M4VH': 'Apple TV',
    'M4VP': 'Apple iPhone',
    'mj2s': 'Motion JPEG 2000 Simple Profile',
    'mjp2': 'Motion JPEG 2000 General Profile',
    'mmp4': 'MPEG-4/3GPP Mobile Profile',
    'mp21': 'MPEG-21',
    'mp41': 'MP4 v1',
    'mp42': 'MP4 v2',
    'mp71': 'MP4 w/ MPEG-7 Metadata',
    'MPPI': 'Photo Player, MAF',
    'mqt ': 'Sony / Mobile QuickTime',
    'MSNV': 'MPEG-4 for SonyPSP',
    'NDAS': 'MP4 v2 Nero Digital AAC Audio',
    'NDSC': 'MPEG-4 Nero Cinema Profile',
    'NDSH': 'MPEG-4 Nero HDTV Profile',
    'NDSM': 'MPEG-4 Nero Mobile Profile',
    'NDSP': 'MPEG-4 Nero Portable Profile',
    'NDSS': 'MPEG-4 Nero Standard Profile',
    'NDXC': 'H.264/MPEG-4 AVC Nero Cinema Profile',
    'NDXH': 'H.264/MPEG-4 AVC Nero HDTV Profile',
    'NDXM': 'H.264/MPEG-4 AVC Nero Mobile Profile',
    'NDXP': 'H.264/MPEG-4 AVC Nero Portable Profile',
    'NDXS': 'H.264/MPEG-4 AVC Nero Standard Profile',
    'odcf': 'OMA DCF DRM Format 2.0',
    'opf2': 'OMA PDCF DRM Format 2.1',
    'opx2': 'OMA PDCF DRM + XBS extensions',
    'pana': 'Panasonic Digital Camera',
    'qt  ': 'Apple QuickTime',
    'ROSS': 'Ross Video',
    'sdv ': 'SD Memory Card Video',
    'ssc1': 'Samsung stereoscopic, single stream',
    'ssc2': 'Samsung stereoscopic, dual stream',
  };
}
