name: ente_utils
description: A Flutter package containing shared utility functions for Ente apps
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^4.0.7
  email_validator: ^3.0.0
  ente_configuration:
    path: ../../packages/configuration
  ente_logging:
    path: ../../packages/logging
  ente_strings:
    path: ../../packages/strings
  ente_ui:
    path: ../../packages/ui
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^7.0.0
  intl: ^0.20.2
  logging: ^1.3.0
  package_info_plus: ^8.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  window_manager: ^0.5.0
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
