include: ../../analysis_options.yaml

analyzer:
  errors:
    deprecated_member_use: warning
  exclude:
    - thirdparty/**
    - lib/generated/**
    - rust_builder/**
    - lib/src/rust/**
    - rust/src/**
    - test/**
