name: ente_accounts
description: A Flutter package containing account-related models, pages, and services for Ente apps
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_links: ^6.3.3
  bip39: ^1.0.6
  collection: ^1.18.0
  dio: ^5.4.0
  dotted_border: ^3.1.0
  email_validator: ^3.0.0
  ente_base:
    path: ../base
  ente_configuration:
    path: ../configuration
  ente_crypto_dart:
    git:
      url: https://github.com/ente-io/ente_crypto_dart.git
  ente_events:
    path: ../events
  ente_lock_screen:
    path: ../lock_screen
  ente_network:
    path: ../network
  ente_strings:
    path: ../strings
  ente_ui:
    path: ../ui
  ente_utils:
    path: ../utils
  file_saver: ^0.3.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  password_strength: ^0.2.0
  pinput: ^5.0.1
  pointycastle: ^3.7.3
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  step_progress_indicator: ^1.0.2
  styled_text: ^8.1.0
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

# This package is not meant to be published
publish_to: none
