name = "github-discord-notifier"
main = "src/index.ts"
compatibility_date = "2024-06-14"

[vars]
# Added as a secret via the Cloudflare dashboard
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/{webhook.id}/{webhook.token}"
