name = "csp-reporter"
main = "src/index.ts"
compatibility_date = "2026-04-23"

routes = [
    { pattern = "csp-reporter.ente.com", custom_domain = true },
    { pattern = "csp-reporter.ente.io", custom_domain = true }
]

tail_consumers = [{ service = "tail" }]
