FROM golang:1.23-alpine3.21@sha256:6c5c9590f169f77c8046e45c611d3b28fe477789acd8d3762d23d4744de69812 AS builder386
RUN apt-get  update
RUN apt-get  install -y gcc
RUN apt-get  install -y git
RUN apt-get  install -y  pkg-config
RUN apt-get  install -y  libsodium-dev


ENV GOOS=linux

WORKDIR /etc/ente/
RUN uname -a
COPY go.mod .
COPY go.sum .
RUN go mod download


COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
     go build -o ente-cli main.go
