blank_issues_enabled: true
contact_links:
    - name: Feature requests and questions
      url: https://github.com/ente-io/ente/discussions
      about: Please use Discussions for everything apart from the above.
