name: ente_network
description: A Flutter package for network management and HTTP client configuration
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  ente_configuration:
    path: ../../packages/configuration
  ente_events:
    path: ../../packages/events
  flutter:
    sdk: flutter
  native_dio_adapter: ^1.4.0
  package_info_plus: ^8.3.0
  ua_client_hints: ^1.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
