name: log_viewer
description: In-app log viewer with filtering capabilities for Ente apps
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logging: ^1.3.0  # For LogRecord type compatibility
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0  # For log export functionality
  sqflite: ^2.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: