import baseConfig from "../../packages/build-config/eslintrc-next-app.mjs";

export default [
    ...baseConfig,
    {
        files: ["**/*.{ts,tsx}"],
        rules: {
            "@typescript-eslint/array-type": "off",
            "@typescript-eslint/consistent-indexed-object-style": "off",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-dynamic-delete": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-meaningless-void-operator": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-non-null-asserted-optional-chain": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unused-vars": "off",
            "@typescript-eslint/non-nullable-type-assertion-style": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/prefer-regexp-exec": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/return-await": "off",
            "no-control-regex": "off",
            "no-unsafe-finally": "off",
            "prefer-const": "off",
        },
    },
];
