FROM golang:1.23.4-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    git \
    libsodium-dev \
    pkg-config \
    postgresql-client \
    socat \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work/server

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

