# https://prometheus.io/docs/prometheus/latest/configuration/

scrape_configs:
    - job_name: museum
      static_configs:
          - targets: ["host.docker.internal:2112"]
      relabel_configs:
          - source_labels: [__address__]
            regex: ".*"
            target_label: instance
            replacement: XX-HOSTNAME

    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
      relabel_configs:
          - source_labels: [__address__]
            regex: ".*"
            target_label: instance
            replacement: XX-HOSTNAME

    - job_name: "node"
      static_configs:
          - targets: ["host.docker.internal:9100"]
      relabel_configs:
          - source_labels: [__address__]
            regex: ".*"
            target_label: instance
            replacement: XX-HOSTNAME

# Grafana Cloud
remote_write:
    - url: https://g/api/prom/push
      basic_auth:
          username: foo
          password: bar
