name: ente_sharing
description: Common sharing functionality for ente apps
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bip39: ^1.0.6
  collection: ^1.17.0
  crypto: ^3.0.6
  dio: ^5.0.0
  dotted_border: ^3.1.0
  ente_accounts:
    path: ../accounts
  ente_configuration:
    path: ../configuration
  ente_crypto_dart:
    git:
      url: https://github.com/ente-io/ente_crypto_dart.git
  ente_network:
    path: ../network
  ente_strings:
    path: ../strings
  ente_ui:
    path: ../ui
  ente_utils:
    path: ../utils
  fast_base58: ^0.2.1
  flutter:
    sdk: flutter
  logging: ^1.0.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
