display_name: Ente Auth
package_name: enteauth
include_build_number: false

maintainer:
  name: Ente Developers
  email: auth@ente.com
priority: optional
section: x11
essential: false
license: GPLv3
icon: assets/generation-icons/icon-windows-linux.png
installed_size: 36000

metainfo: linux/packaging/enteauth.appdata.xml

dependencies:
  - libsqlite3-0
  - libsodium23
  - libsecret-1-0
  - policykit-1 | polkitd
  - libappindicator3-1 | libayatana-appindicator3-1
  - gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1
  - libayatana-ido3-0.4-0

postinstall_scripts:
  - install -D -o root -g root -m 0644 /usr/share/enteauth/data/flutter_assets/assets/polkit/io.ente.auth.policy /usr/share/polkit-1/actions/io.ente.auth.policy
  - if command -v chcon >/dev/null 2>&1; then chcon system_u:object_r:usr_t:s0 /usr/share/polkit-1/actions/io.ente.auth.policy || true; fi

postuninstall_scripts:
  - rm -f /usr/share/polkit-1/actions/io.ente.auth.policy

keywords:
  - Authentication
  - 2FA

generic_name: Ente Authenticator

categories:
  - Utility

startup_notify: false
startup_wm_class: io.ente.auth

supported_mime_type:
  - x-scheme-handler/enteauth
