name: photos_tv
description: Ente Photos TV receiver
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  ente_crypto_api:
    path: ../../packages/ente_crypto_api
  ente_crypto_dart_adapter:
    path: ../../packages/ente_crypto_dart_adapter
  flutter:
    sdk: flutter
  http: 1.6.0

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
