import { FFmpeg } from "@ffmpeg/ffmpeg";
import { newID } from "ente-base/id";
import log from "ente-base/log";
import type { FFmpegCommand } from "ente-base/types/ipc";
import { PromiseQueue } from "ente-utils/promise";
import z from "zod";
import {
    ffmpegPathPlaceholder,
    inputPathPlaceholder,
    outputPathPlaceholder,
} from "./constants";

/** Lazily initialized and loaded FFmpeg instance. */
let _ffmpeg: Promise<FFmpeg> | undefined;

/** Queue of in-flight requests. */
const _ffmpegTaskQueue = new PromiseQueue<Uint8Array>();

/**
 * Return the shared {@link FFmpeg} instance, lazily creating and loading it if
 * needed.
 */
const ffmpegLazy = (): Promise<FFmpeg> => (_ffmpeg ??= createFFmpeg());

const createFFmpeg = async () => {
    const ffmpeg = new FFmpeg();
    await ffmpeg.load({
        coreURL: "https://assets.ente.io/ffmpeg-core-0.12.10/ffmpeg-core.js",
        wasmURL: "https://assets.ente.io/ffmpeg-core-0.12.10/ffmpeg-core.wasm",
    });
    // This is too noisy to enable even during development. Uncomment to taste.
    // ffmpeg.on("log", (e) => log.debug(() => ["[ffmpeg]", e.message]));
    return ffmpeg;
};

/**
 * Run the given FFmpeg command using a Wasm FFmpeg running in a web worker.
 *
 * This is a sibling of {@link ffmpegExec} exposed by the desktop app in
 * `ipc.ts`. As a rough ballpark, currently the native FFmpeg integration in the
 * desktop app is 10-20x faster than the Wasm one.
 *
 * See: [Note: FFmpeg in Electron].
 *
 * @param command The FFmpeg command to execute.
 *
 * @param blob The input data on which to run the command, provided as a blob.
 *
 * @param outputFileExtension The extension of the (temporary) output file which
 * will be generated by the command.
 *
 * @returns The contents of the output file generated as a result of executing
 * {@link command} on {@link blob}.
 */
export const ffmpegExecWeb = async (
    command: FFmpegCommand,
    blob: Blob,
    outputFileExtension: string,
): Promise<Uint8Array> => {
    const ffmpeg = await ffmpegLazy();
    // Interleaving multiple ffmpeg.execs causes errors like
    //
    // >  "Out of bounds memory access (evaluating 'Module["_malloc"](len)')"
    //
    // So serialize them using a promise queue.
    return _ffmpegTaskQueue.add(() =>
        ffmpegExec(ffmpeg, command, outputFileExtension, blob),
    );
};

const ffmpegExec = async (
    ffmpeg: FFmpeg,
    command: FFmpegCommand,
    outputFileExtension: string,
    blob: Blob,
) => {
    const inputPath = newID("in_");
    const outputSuffix = outputFileExtension ? "." + outputFileExtension : "";
    const outputPath = newID("out_") + outputSuffix;

    const inputData = new Uint8Array(await blob.arrayBuffer());

    // Exit status of the ffmpeg.exec invocation.
    // `0` if no error, `!= 0` if timeout (1) or error.
    let status: number | undefined;

    try {
        const startTime = Date.now();

        await ffmpeg.writeFile(inputPath, inputData);

        const resolvedCommand = Array.isArray(command)
            ? command
            : command.default;

        const cmd = substitutePlaceholders(
            resolvedCommand,
            inputPath,
            outputPath,
        );

        status = await ffmpeg.exec(cmd);
        if (status !== 0) {
            log.info(
                `[wasm] ffmpeg command failed with exit code ${status}: ${cmd.join(" ")}`,
            );
            throw new Error(`ffmpeg command failed with exit code ${status}`);
        }

        const result = await ffmpeg.readFile(outputPath);
        if (typeof result == "string") throw new Error("Expected binary data");

        const ms = Date.now() - startTime;
        log.debug(() => `[wasm] ffmpeg ${cmd.join(" ")} (${ms} ms)`);
        return result;
    } finally {
        try {
            await ffmpeg.deleteFile(inputPath);
        } catch (e) {
            log.error(`Failed to remove input ${inputPath}`, e);
        }
        try {
            await ffmpeg.deleteFile(outputPath);
        } catch (e) {
            // Output file might not even exist if the command did not succeed,
            // so only log on success.
            if (status === 0) {
                log.error(`Failed to remove output ${outputPath}`, e);
            }
        }
    }
};

const substitutePlaceholders = (
    command: string[],
    inputFilePath: string,
    outputFilePath: string,
) =>
    command
        .map((segment) => {
            if (segment == ffmpegPathPlaceholder) {
                return undefined;
            } else if (segment == inputPathPlaceholder) {
                return inputFilePath;
            } else if (segment == outputPathPlaceholder) {
                return outputFilePath;
            } else {
                return segment;
            }
        })
        .filter((s) => s !== undefined);

const isHDRVideoFFProbeOutput = z.object({
    streams: z.array(z.object({ color_transfer: z.string().optional() })),
});

/**
 * A variant of the {@link isHDRVideo} function in the desktop app source (see
 * `ffmpeg.ts`), except here we have access to ffprobe and can use that instead
 * of parsing the ffmpeg stderr.
 *
 * See: [Note: Alternative FFmpeg command for HDR videos]
 *
 * @param inputFilePath The path to a video file on the FFmpeg FS.
 *
 * @returns `true` if this file is likely a HDR video. Exceptions are treated as
 * `false` to make this function safe to invoke without breaking the happy path.
 */
const isHDRVideo = async (ffmpeg: FFmpeg, inputFilePath: string) => {
    try {
        const jsonString = await ffprobeOutput(
            ffmpeg,
            [
                ["-i", inputFilePath],
                // Show information about streams.
                "-show_streams",
                // Select the first video stream (This is not necessarily
                // correct in a multi stream file since the highest resolution
                // stream will be used in the automatic mapping). But this is a
                // heuristic check anyway.
                ["-select_streams", "v:1"],
                // Output JSON
                ["-of", "json"],
                ["-o", "output.json"],
            ].flat(),
            "output.json",
        );

        const output = isHDRVideoFFProbeOutput.parse(JSON.parse(jsonString));
        switch (output.streams[0]?.color_transfer) {
            case "smpte2084":
            case "arib-std-b67":
                return true;
            default:
                return false;
        }
    } catch (e) {
        log.warn(`Could not detect HDR status of ${inputFilePath}`, e);
        return false;
    }
};

/**
 * Return the textual output produced by verbatim invoking the given ffprobe
 * {@link cmd} that is expected to writes to a file named {@link outputFilePath}
 * in the FFmpeg FS.
 *
 * The file generated at {@link outputFilePath} is removed in all cases.
 */
const ffprobeOutput = async (
    ffmpeg: FFmpeg,
    cmd: string[],
    outputPath: string,
) => {
    // Exit status of the ffmpeg.ffprobe invocation.
    // `0` if no error, `!= 0` if timeout (1) or error.
    let status: number | undefined;

    try {
        status = await ffmpeg.ffprobe(cmd);
        // Currently, ffprobe incorrectly returns status -1 on success.
        // https://github.com/ffmpegwasm/ffmpeg.wasm/issues/817
        if (status !== 0 && status != -1) {
            log.info(
                `[wasm] ffprobe command failed with exit code ${status}: ${cmd.join(" ")}`,
            );
            throw new Error(`ffprobe command failed with exit code ${status}`);
        }

        const result = await ffmpeg.readFile(outputPath, "utf8");
        if (typeof result != "string") throw new Error("Expected text data");

        return result;
    } finally {
        try {
            await ffmpeg.deleteFile(outputPath);
        } catch (e) {
            // Output file might not even exist if the command did not succeed,
            // so only log on success.
            if (status !== 0 && status != -1) {
                log.error(`Failed to remove output ${outputPath}`, e);
            }
        }
    }
};
