desc "Download iOS screenshots"
lane :download_ios_screenshots do
  user_name = ENV["APPLE_USER_NAME"]
  bundle_id = ENV["PHOTOS_APP_BUNDLE_ID"]
  sh("fastlane deliver download_screenshots -w './metadata/ios/Screenshots' -u '#{user_name}' -a '#{bundle_id}' --use_live_version true --metadata_path './metadata/ios'")
end

