import Foundation

extension Data {
    /// Encode data as URL-safe base64 (RFC 4648 §5), **without padding**.
    func base64URLEncodedString() -> String {
        let b64 = self.base64EncodedString()
        return b64
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    /// Encode data as URL-safe base64 (RFC 4648 §5), **with padding**.
    ///
    /// Ente auth tokens are generated by the server using Go's `base64.URLEncoding`,
    /// which is URL-safe **and includes padding**. Clients must preserve padding
    /// when re-encoding token bytes.
    func base64URLPaddedEncodedString() -> String {
        let b64 = self.base64EncodedString()
        return b64
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
    }

    /// Decode a URL-safe base64 string (with or without padding).
    init?(base64URLString: String) {
        var s = base64URLString
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        let remainder = s.count % 4
        if remainder != 0 {
            s.append(String(repeating: "=", count: 4 - remainder))
        }
        self.init(base64Encoded: s)
    }
}
