name: backup_exclusion
description: iOS backup exclusion utilities for Ente Flutter apps
version: 1.0.0
homepage: https://github.com/ente-io/ente
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  logging: 1.3.0

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BackupExclusionPlugin
