name: "Release (copycat-db)"

on:
    workflow_dispatch: # Run manually

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Check out code

            - uses: mr-smithers-excellent/docker-build-push@v6
              name: Build & Push
              with:
                  dockerfile: infra/copycat-db/Dockerfile
                  directory: infra/copycat-db
                  image: ente/copycat-db
                  registry: rg.fr-par.scw.cloud
                  enableBuildKit: true
                  buildArgs: GIT_COMMIT=${GITHUB_SHA}
                  tags: ${GITHUB_SHA}, latest
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
