name: "Verify build (docs)"

# Preflight build of docs. This allows us to ensure that npm run build is
# succeeding before we merge the PR into main.

on:
    # Run on every pull request (open or push to it) that changes docs/
    pull_request:
        paths:
            - "docs/**"
            - ".github/workflows/docs-verify-build.yml"

permissions:
    contents: read

jobs:
    verify-build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: docs

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
                  cache-dependency-path: "docs/package-lock.json"

            - run: npm ci

            - run: npm audit --audit-level=critical

            - run: npm run build
