name: "Verify build (docs)"

# Preflight build of docs. This allows us to ensure that npm run build is
# succeeding before we merge the PR into main.

on:
    # Run on every pull request (open or push to it) that changes docs/
    pull_request:
        paths:
            - "docs/**"
            - ".github/workflows/docs-verify-build.yml"

permissions:
    contents: read

jobs:
    verify-build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: docs

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup node and enable npm caching
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
                  cache-dependency-path: "docs/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Build production site
              run: npm run build
