name: "Lint (locker)"

on:
    # Run on every pull request (open or push to it) that changes locker app
    pull_request:
        paths:
            - "mobile/apps/locker/**"
            - "mobile/packages/contacts/**"
            - "mobile/packages/legacy/**"
            - "mobile/packages/rust/**"
            - "mobile/packages/sharing/**"
            - ".github/workflows/locker-lint.yml"

env:
    FLUTTER_VERSION: "3.32.8"
    RUST_VERSION: "1.90.0"

permissions:
    contents: read

jobs:
    locker-lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: mobile/apps/locker
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Verify frozen mobile pubspecs
              run: ruby mobile/scripts/check_frozen_pubspecs.rb mobile/apps/locker
              working-directory: ${{ github.workspace }}

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - name: Install Rust ${{ env.RUST_VERSION }}
              uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
              with:
                  toolchain: ${{ env.RUST_VERSION }}

            - name: Cache Rust dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      mobile/packages/rust/rust/target
                  key: ${{ runner.os }}-cargo-locker-${{ hashFiles('mobile/packages/**/Cargo.lock') }}

            - name: Install Flutter Rust Bridge
              run: cargo install flutter_rust_bridge_codegen

            - name: Generate Rust bindings (Core package)
              run: flutter_rust_bridge_codegen generate
              working-directory: mobile/packages/rust

            - name: Generate strings localizations
              run: flutter gen-l10n
              working-directory: mobile/packages/strings

            - run: flutter pub get --enforce-lockfile

            - run: flutter analyze --no-fatal-infos
