name: "Internal release (locker mobile)"

on:
    workflow_dispatch: # Allow manually running the action

env:
    FLUTTER_VERSION: "3.32.8"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: mobile/apps/locker

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - name: Setup keys
              uses: timheuer/base64-to-file@v1
              with:
                  fileName: "keystore/ente_locker_key.jks"
                  encodedString: ${{ secrets.SIGNING_KEY_LOCKER }}

            - name: Build PlayStore AAB
              run: |
                  flutter build appbundle --release
              env:
                  SIGNING_KEY_PATH: "/home/runner/work/_temp/keystore/ente_locker_key.jks"
                  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS_LOCKER }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD_LOCKER }}
                  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD_LOCKER }}

            - name: Upload AAB to PlayStore
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_LOCKER }}
                  packageName: io.ente.locker
                  releaseFiles: mobile/apps/locker/build/app/outputs/bundle/release/app-release.aab
                  track: internal

            - name: Notify Discord
              uses: sarisia/actions-status-discord@v1
              with:
                  webhook: ${{ secrets.DISCORD_INTERNAL_RELEASE_WEBHOOK }}
                  nodetail: true
                  title: "🔒 Internal release available for Locker"
                  description: "[Download](https://play.google.com/store/apps/details?id=io.ente.locker)"
                  color: 0x4CAF50