name: "Release (server)"

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Log in to Docker registry
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: printf '%s' "${DOCKER_PASSWORD}" | docker login rg.fr-par.scw.cloud --username "${DOCKER_USERNAME}" --password-stdin

            - name: Build and push image
              run: |
                  docker buildx build --push \
                      --file server/Dockerfile \
                      --build-arg GIT_COMMIT="${GITHUB_SHA}" \
                      --tag rg.fr-par.scw.cloud/ente/museum-prod:${GITHUB_SHA} \
                      --tag rg.fr-par.scw.cloud/ente/museum-prod:latest \
                      server
