name: "Publish GHCR (Server)"

on:
    # Run automatically on 15th of every month, at 05:00 UTC.
    schedule:
        - cron: '0 5 15 * *'
    # Run manually if needed to publish out of schedule.
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Determine commit from prod museum
              run: |
                  museum_commit="$(curl -s https://api.ente.com/ping | jq -r .id)"
                  [[ "${museum_commit}" =~ ^[0-9a-f]{40}$ ]]
                  echo "museum_commit=${museum_commit}" >> $GITHUB_ENV

            - name: Checkout prod museum commit
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                  ref: ${{ env.museum_commit }}

            - name: Log in to GHCR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: printf '%s' "${GITHUB_TOKEN}" | docker login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin

            - name: Build and push
              run: |
                  docker buildx create --use
                  docker buildx build --push \
                      --file server/Dockerfile \
                      --platform linux/amd64,linux/arm64 \
                      --build-arg GIT_COMMIT="${museum_commit}" \
                      --tag ghcr.io/ente-io/server:${museum_commit} \
                      --tag ghcr.io/ente-io/server:latest \
                      server
