name: "Lint (Server)"

on:
    pull_request:
        paths:
            - ".github/workflows/server-lint.yml"
            - "server/**"

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup go
              uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
              with:
                  go-version-file: server/go.mod
                  cache-dependency-path: server/go.sum
                  cache: true

            - name: Lint
              run: ./scripts/lint.sh

            - name: Test
              run: ./scripts/test-with-postgres.sh docker
