name: "Deploy (Web)"

on:
    schedule:
        # [Note: Run workflow every 24 hours]
        #
        # Run every weekday at ~8:00 AM IST.
        #
        # First field is minute, second is hour of the day. Last is day of week,
        # 0 being Sunday.
        #
        # Add a few minutes of offset to avoid scheduling on exact hourly
        # boundaries (recommended by GitHub to avoid congestion).
        #
        # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
        # https://crontab.guru/
        #
        - cron: "25 2 * * 1-5"
    # Also allow manually running the workflow
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Setup node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 24
                  cache: "npm"
                  cache-dependency-path: "web/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Audit dependencies
              run: npm audit --audit-level critical
            - name: Deploy photos
              uses: ./.github/actions/deploy-web-app
              with:
                  app: photos
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy albums
              uses: ./.github/actions/deploy-web-app
              with:
                  app: albums
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy accounts
              uses: ./.github/actions/deploy-web-app
              with:
                  app: accounts
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy auth
              uses: ./.github/actions/deploy-web-app
              with:
                  app: auth
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy legacy
              uses: ./.github/actions/deploy-web-app
              with:
                  app: legacy
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy cast
              uses: ./.github/actions/deploy-web-app
              with:
                  app: cast
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy payments
              uses: ./.github/actions/deploy-web-app
              with:
                  app: payments
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  output: dist

            - name: Deploy locker
              uses: ./.github/actions/deploy-web-app
              with:
                  app: locker
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy share
              uses: ./.github/actions/deploy-web-app
              with:
                  app: share
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy memories
              uses: ./.github/actions/deploy-web-app
              with:
                  app: memories
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy paste
              uses: ./.github/actions/deploy-web-app
              with:
                  app: paste
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy embed
              uses: ./.github/actions/deploy-web-app
              with:
                  app: embed
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            - name: Deploy ensu
              uses: ./.github/actions/deploy-web-app
              with:
                  app: ensu
                  account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
