name: "Publish GHCR (Web)"

on:
    # Run automatically every Wednesday, at 07:00 UTC.
    schedule:
        - cron: '0 7 * * 3'
    # Run manually if needed to publish out of schedule.
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Log in to GHCR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: printf '%s' "${GITHUB_TOKEN}" | docker login ghcr.io --username "${GITHUB_ACTOR}" --password-stdin

            - name: Build and push
              run: |
                  docker buildx create --use
                  docker buildx build --push \
                      --file web/Dockerfile \
                      --platform linux/amd64,linux/arm64 \
                      --tag ghcr.io/ente/web:${GITHUB_SHA} \
                      --tag ghcr.io/ente/web:latest \
                      .
