name: local_auth_linux
description: Linux implementation of the local_auth plugin for Ente.

resolution: workspace
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: local_auth
    platforms:
      linux:
        pluginClass: LocalAuthLinuxPlugin
        dartPluginClass: LocalAuthLinux

dependencies:
  flutter:
    sdk: flutter
  local_auth_platform_interface: 1.1.0

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
